### ISSUE TITLE
MaterialDesignFloatingHintTextBox bug

### ISSUE THREAD

**Issue by Drarig29** [ButchersBoy/MaterialDesignInXamlToolkit#578] opened 2016-12-19 19:16 UTC
With the MaterialDesignFloatingHintTextBox style, when we start to write in the TextBox, the hint starts floating. But if I write spaces, it doesn't.

**Comment by ButchersBoy** [comment] 2016-12-20 08:48
Duplicate of #574

**Closed by ButchersBoy** 2016-12-20 08:48 UTC
