### ISSUE TITLE
More than one PopupBox (MaterialDesignMultiFloatingActionPopupBox)

### ISSUE THREAD

**Issue by hshahdoost** [ButchersBoy/MaterialDesignInXamlToolkit#338] opened 2016-04-12 12:48 UTC
Having more than one Popupbox with floating action style would cause a bug, which the first one's icon is disappeared.

![popupbox](https://cloud.githubusercontent.com/assets/1842220/14460350/56c2dc5e-00d2-11e6-84f0-aa2ceeb92ab4.png)

the code:

	<materialDesign:PopupBox Style="{StaticResource MaterialDesignMultiFloatingActionPopupBox}"
							 PlacementMode="BottomAndAlignCentres"
							 ToolTipService.Placement="Bottom"
							 ToolTip="PopupBox, Style MaterialDesignMultiFloatingActionPopupBox">
		<StackPanel>
			<Button ToolTip="One">1</Button>
			<Button ToolTip="Two">2</Button>
			<Button ToolTip="Three">3</Button>
		</StackPanel>
	</materialDesign:PopupBox>
	<materialDesign:PopupBox Style="{StaticResource MaterialDesignMultiFloatingActionPopupBox}"
							 PlacementMode="BottomAndAlignCentres"
							 ToolTipService.Placement="Bottom"
							 ToolTip="PopupBox, Style MaterialDesignMultiFloatingActionPopupBox">
		<StackPanel>
			<Button ToolTip="One">1</Button>
			<Button ToolTip="Two">2</Button>
			<Button ToolTip="Three">3</Button>
		</StackPanel>
	</materialDesign:PopupBox>

**Comment by hshahdoost** [comment] 2016-04-12 13:08
Here is a more specific sample:

**Comment by ButchersBoy** [comment] 2016-04-12 13:12
Duplicate of https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/291

**Closed by ButchersBoy** 2016-04-12 13:12 UTC
