### ISSUE TITLE
HintAssist can't find problem

### ISSUE THREAD

**Issue by tycallen** [ButchersBoy/MaterialDesignInXamlToolkit#467] opened 2016-08-23 06:58 UTC
Sorry it's a stupid question but how can I solve this problem
![image](https://cloud.githubusercontent.com/assets/3022000/17882885/d081db58-6941-11e6-951b-053ebb4518b1.png)

**Comment by ButchersBoy** [comment] 2016-08-23 08:15
Have you recently upgraded to 2.0?  If so a full clean and rebuild might fix it...

**Comment by ButchersBoy** [comment] 2016-08-26 14:37
Closing this as it's not a bug.  If you want help please hit up the gitter channel.

**Closed by ButchersBoy** 2016-08-26 14:37 UTC
