### ISSUE TITLE
MaterialDesignFloatingHintTextBox not displaying hint correctly

### ISSUE THREAD

**Issue by gregor4005** [ButchersBoy/MaterialDesignInXamlToolkit#231] opened 2016-01-26 16:19 UTC
Hey, first I want to thank you for your great work :smile: 
Since the update from 1.3.1 to 1.4 I have a small issue regarding the rendering of the floating hint in textboxes.
The bound values for the textboxes in my startup-control are initialized with default values in the constructor.
Before updating to 1.4 the floating hint was placed above the content (as it should be).
After updating to 1.4 the floating hint is placed behind the content (wrong behaviour).
![glitch](https://cloud.githubusercontent.com/assets/10714600/12586231/baeb43de-c44f-11e5-8ca2-22aad5ceeaf0.png)

If I switch to another control and back to the startup-control, the hint is placed above the content (right behaviour).
At design-time everything looks fine.

**Comment by ButchersBoy** [comment] 2016-01-26 16:20
Hi, are you running on latest pre-release?  (1.4.1.x)

**Comment by gregor4005** [comment] 2016-01-26 17:27
I am currently running the latest stable. I will try the latest pre-release and tell you the result.

**Comment by hshahdoost** [comment] 2016-01-26 18:38
If you're using a TemplateSelector I think I know what is the cause of this problem. I've faced the similar problem and been able to temporarily solve it by removing ManagedPropertyChangedCallback from TextFieldAssist. I know it's not a permanent solution but I might have found the reason why this bug happens.

It's because the state of TextBoxHint is being set twice after the form loads. Once in TextPropertyChangedCallback on the Loaded event. which is the right one and the other on RefreshState right after the control appears on the screen. The reason why the second call takes the control to the wrong state is that IsVisibleChanged event is being called before the binding happens. and while there is no text on the textbox. but for some unknown reason it changes the object's state using Dispatcher.BeginInvoke which makes the queue on the SynchronizationContext (I guess it's what it's called :) ). and for some reason Loaded event which is the right one happens right after the IsVisibleChanged, changes the object state to the right state but right after that the queued code comes and changes the state of HintText to the wrong state. 

I have checked these steps on my debugger for multiple times. I might have made a mistake understanding why they happen like this but I know it is the cause of this bug.

**Comment by ButchersBoy** [comment] 2016-01-26 19:38
@hshahdoost thanks for the info.

**Comment by ButchersBoy** [comment] 2016-01-27 12:38
I've added some stuff to the demo to test templates, but I wasn't able to reproduce.  _However_ someone had kindly sent me a repo with another example in a dialog (no - I havent added that example to the demo) which shows the error.

Seems to be fixed now, but please report back.

**Comment by hshahdoost** [comment] 2016-01-27 16:31
I checked it and it's fixed. thanks a lot.
There is just one thing. The following lines in **TextPropertyChangedCallback** seem to useless now. I removed them and everything worked just fine.

```c#
frameworkElement.Loaded += (sender, args) => VisualStateManager.GoToState(frameworkElement, state, false);
frameworkElement.IsVisibleChanged += (sender, args) => VisualStateManager.GoToState(frameworkElement, state, true);
```

**Comment by ButchersBoy** [comment] 2016-01-27 16:32
You want to raise a PR with that?

**Comment by hshahdoost** [comment] 2016-01-27 16:36
I'm thinking more like it's a part of the bug. But if you think it's necessary to raise a PR I'll do that.

**Comment by ButchersBoy** [comment] 2016-01-27 16:37
Just thought you might want credit :)

**Comment by ButchersBoy** [comment] 2016-01-28 11:01
Just code reviewing it again.  I think I am going to leave those handlers in place.  Attached properites get applied after first load (I _think_, correct me if I'm wrong).  So if a control is loaded > managed property applied > unloaded > text changes...then you need to wait for next load to reapply the state.

So I think this should have some more of the complex load flows covered.

**Closed by ButchersBoy** 2016-01-28 11:01 UTC
Labels: in progress

**Comment by hshahdoost** [comment] 2016-02-03 05:28
Sorry, for the delay, and also sorry for the mistake I made. You were right. I checked it and ManagedPropertyChangedCallback is not called when the form is reloaded.

**Comment by Sergey-Terekhin** [comment] 2016-05-06 07:08
Hi! I'm using the latest stable version from NuGet (1.5.0.523), and bug is still here:

![2016-05-06 10 03 07](https://cloud.githubusercontent.com/assets/5369802/15066499/2f977db2-1372-11e6-9982-f0d15e29abe3.png)

Then I select or enter value, anything works fine - hint flies away. But if I change active tab and return back, all hints are below entered or selected values

**Comment by ButchersBoy** [comment] 2016-05-06 07:42
And on 2.0?

**Comment by Sergey-Terekhin** [comment] 2016-05-06 08:46
I'll check
