### ISSUE TITLE
Combobox selected item color

### ISSUE THREAD

**Issue by Spyspyspy** [ButchersBoy/MaterialDesignInXamlToolkit#553] opened 2016-11-17 07:59 UTC
Hello. Your toolkit is awesome. How can I change the purple color into another, when I select item? Is it possible?
![test](https://cloud.githubusercontent.com/assets/22395104/20380717/6e83465e-acac-11e6-9b62-945cb45ee677.JPG)

**Comment by ButchersBoy** [comment] 2016-11-17 08:21
The WPF ComboBox only supports a single foreground colour, so you probably would have to merge in a resource dictionary on the fly and change ``` PrimaryHueMidBrush ```.

So probably doable, but depends you your WPF knowledge.

**Comment by ButchersBoy** [comment] 2016-11-17 12:53
Closing is this is not a bug.  Feel free to enter our Gitter chat room for more general conversation.

**Closed by ButchersBoy** 2016-11-17 12:53 UTC
