### ISSUE TITLE
Allow dialog box/drawer overlay color/opacity to be changed 

### ISSUE THREAD

**Issue by StealthRT** [ButchersBoy/MaterialDesignInXamlToolkit#588] opened 2017-01-12 04:05 UTC
Would be helpful if we could change the overlay color and opacity of the dialog box and also the drawer.

@ButchersBoy

**Comment by ButchersBoy** [comment] 2017-01-17 16:30
closing, dupe of #568

**Closed by ButchersBoy** 2017-01-17 16:30 UTC
