### ISSUE TITLE
DemoItem.Content UserControl

### ISSUE THREAD

**Issue by SiNcSaD** [ButchersBoy/MaterialDesignInXamlToolkit#240] opened 2016-02-03 10:47 UTC
My problem , look Gif!
Page1 ==>Window
Sliders==>UserControl (ref: Demo xaml)
Click Sliders , not display Slider.xaml
help me!!!
```xaml
<ListBox x:Name="ItemsListBox" Margin="0 16 0 16" SelectedIndex="0"
               PreviewMouseLeftButtonUp="UIElement_OnPreviewMouseLeftButtonUp">
       <ListBox.ItemTemplate>
             <DataTemplate DataType="item:Items">
                    <TextBlock Text="{Binding Title}" Margin="32 0 32 0" Foreground="Red"/>
             </DataTemplate>
       </ListBox.ItemTemplate>
       <item:Items Title="PAGE">
             <item:Items.Content>
                    <local:Page1 />
             </item:Items.Content>
       </item:Items>
       <item:Items Title="Sliders">
              <item:Items.Content>
                     <local:Sliders />
              </item:Items.Content>
        </item:Items>
</ListBox>
```

![untitled](https://cloud.githubusercontent.com/assets/17000388/12779734/a7f3dc36-caa4-11e5-8a91-0f076d156ddf.gif)

```CSHARP
public class Items
{
     public string Title { get; set; }
     public object Content { get; set; }
}
```

**Comment by ButchersBoy** [comment] 2016-02-03 10:53
Hi...I can't see all your code to see what the issue is.  Something must be missing.

Have you got this set up correctly? 

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/MainWindow.xaml#L190

**Comment by SiNcSaD** [comment] 2016-02-03 12:11
Before
```xaml
<ContentControl Margin="16" Content="{Binding ElementName=DemoItemsListBox, Path=SelectedItem.Content}" />
```
After
```xaml
<ContentControl Margin="16" Content="{Binding ElementName=ItemsListBox, Path=SelectedItem.Content}" />
```
thank you , The successful resolution of this issue.
But now I want [Content Window]...not Control
because i used to Windows .

**Comment by ButchersBoy** [comment] 2016-02-03 12:15
Not sure I understand this question.  Do you want to put a Window in there?

**Comment by SiNcSaD** [comment] 2016-02-03 15:19
Yes , I want to put a Window.
<img width="665" alt="default" src="https://cloud.githubusercontent.com/assets/17000388/12786535/7cc78b7a-cacc-11e5-8fdd-3e1e7c73ada2.png">

**Comment by ButchersBoy** [comment] 2016-02-03 15:20
You can't do that.  WPF won't let you.  You will have to move your existing Window content into a UserControl.

**Comment by ButchersBoy** [comment] 2016-02-03 16:29
Not an issue, WPF constraint, closing.

**Closed by ButchersBoy** 2016-02-03 16:29 UTC
